#!/usr/bin/env bash
# .devcontainer/init.sh
#
# Assumed to be called from the initializeCommand of VS Code Dev Containers.
# 1. Determine COMPOSE_PROJECT_NAME by concatenating the project name and the host user name.
# 2. Write the host UID/GID to the .env file.
# -------------------------------------------------------------

set -euo pipefail

# Get the root (workspace) directory.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DIR="$(dirname "$SCRIPT_DIR")"

# 1) COMPOSE_PROJECT_NAME = <username>-<basename> (converted to lowercase alphanumerics)
host_user="$(id -un | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9_-')"
project_basename="$(basename "$WORKSPACE_DIR" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9_-')"
COMPOSE_PROJECT_NAME="${host_user}-${project_basename}"

# 2) UID / GID
USER_ID="$(id -u)"
GROUP_ID="$(id -g)"

# Write to .env
cat > "${WORKSPACE_DIR}/.env" <<EOF
# Auto-generated by .devcontainer/init.sh
COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
USER_ID=${USER_ID}
GROUP_ID=${GROUP_ID}
EOF

echo ".env generated at ${WORKSPACE_DIR}/.env:"
cat "${WORKSPACE_DIR}/.env"
