#!/usr/bin/env bash
# .devcontainer/init.sh
#
# VS Code Dev Containers の initializeCommand から呼び出される前提。
# 1. プロジェクト名 と ホストユーザー名 を結合して COMPOSE_PROJECT_NAME を決定
# 2. ホストの UID/GID を .env に書き出し
# -------------------------------------------------------------

set -euo pipefail

# ルート（= ワークスペース）ディレクトリを取得
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DIR="$(dirname "$SCRIPT_DIR")"

# 1) COMPOSE_PROJECT_NAME = <username>-<basename> （小文字・英数字に整形）
host_user="$(id -un | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9_-')"
project_basename="$(basename "$WORKSPACE_DIR" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9_-')"
COMPOSE_PROJECT_NAME="${host_user}-${project_basename}"

# 2) UID / GID
USER_ID="$(id -u)"
GROUP_ID="$(id -g)"

# .env に書き出す
cat > "${WORKSPACE_DIR}/.env" <<EOF
# Auto-generated by .devcontainer/init.sh
COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
USER_ID=${USER_ID}
GROUP_ID=${GROUP_ID}
EOF

echo ".env generated at ${WORKSPACE_DIR}/.env:"
cat "${WORKSPACE_DIR}/.env"
